seed: 0

dataset:
  _target_: src.dataset.dataset.CIFAR100Dataset
  root: '~/feature_alignment/data'
  batch_size: 64 
  params:
    img_size: 64 

model:
  _target_: src.model.sit.SiT_B_2
  params:
    qk_norm: true
    input_size: 64
    in_channels: 3
    num_classes: 100
    class_dropout_prob: 0.1
    use_cfg: true
    use_register_tokens: true
    num_register_tokens: 2

trainer:
  _target_: src.trainer.flow_matching_trainer.FlowMatchingTrainer
  num_epochs: 100
  device: 'cuda:0'
  load_checkpoint_path: null
  save_checkpoint_dir: ~/feature_alignment/ckpts/sits2_cifar64
  save_checkpoint_interval: 10000
  params:
    lr: 1e-4
    img_encoder: null 